user:
    maxwellUsername: bornemaf
directory:
    outputParentDirectory: /beegfs/desy/user/${maxwellUsername}/data/syreal_output
    feynmanDatapoints: /beegfs/desy/user/${maxwellUsername}/Feynman/Feynman_with_units