# SCHEDULER CONFIG
WORKER_NUM: 10
PARALLEL_PROCS: 60
WORKER_TIMEOUT: "05:00:00"
SCHEDULER_INTERVAL: 30
BACKUP_INTERVAL: 10 # time of scheduler interval before backup

# USER CONFIG
EMAIL: "syreal_jobs@outlook.com"
JOBS_DIR: "/beegfs/desy/user/bornemaf/data/syreal_output/GridSearch_Experiment"
SLURM_USER: "bornemaf"
SLURM_PARTITION: "allcpu"
PYTHON_SCRIPT: "parallel.py"
ENV: "PySR"

# JOB CONFIG
JOB_STATUS: ["running", "finished", "stopped", "pending"]

# SYREAL CONFIG
LOSS_THRESHOLD: 1.e-7
MAX_ITERATIONS: 500
PROCS: 0 # 0 = no multithreading. Every process will run on a single thread
