# SCHEDULER CONFIG
WORKER_NUM: 10
PARALLEL_PROCS: 2
WORKER_TIMEOUT: 7200
SCHEDULER_INTERVAL: 30

# USER CONFIG
EMAIL: "syreal_jobs@outlook.com"
JOBS_DIR: "/beegfs/desy/user/bornemaf/data/syreal_output/job_testing"
SLURM_USER: "bornemaf"
SLURM_PARTITION: "allcpu"
PYTHON_SCRIPT_FILE: "parallel.py"

# JOB CONFIG
JOB_STATUS: ["running", "finished", "stopped", "pending"]

# SYREAL CONFIG
LOSS_THRESHOLD: 1e-7
MAX_ITERATIONS: 500
